### ISSUE TITLE
How to create definitions from local files?

### ISSUE THREAD

**Issue by camilo1729** [YorickPeterse/ruby-lint#159]
Hello,
Great job with this gem, it is what I was looking for. Is is possible to create definitions from files that are not still in a gem? In my specific example I have a file called `utils.rb` where I defined a some methods and classes. This file look like this: 

```ruby 
def check_cpu_performance(machines,ref_value)
  badnodes = {}
  Net::SSH::Multi.start do |session|
    machines.each{ |node| session.use("root@#{node}")}
    session.exec! ""
    session.exec! "DEBIAN_FRONTEND=noninteractive apt-get install -q -y sysbench"
    results = session.exec! "sysbench --num-threads=16 --test=cpu run --cpu-max-prime=100000 | grep \"execution time\" | awk '{print $4}' | cut -d / -f 1"
    puts results
    badnodes = results.select{ |name,res| res[:stdout].to_i > (ref_value +2)}
  end
  badnodes.keys
end


class MultiIO
  def initialize(*targets)
     @targets = targets
  end

  def write(*args)
    @targets.each {|t|
      t.write(*args)
      # this is just to assure a coherent log for multiple scripts
      t.flush
    }

  end

  def close
    @targets.each(&:close)
  end
end


```

Then I load this file from another script. Is it possible to generate a definition file for this file?.
Thank you.

**Comment by YorickPeterse** [comment]
If `MultiIO` is referenced anywhere it should be picked up automatically by ruby-lint if the corresponding file is called `multi_io.rb`. Generating definitions is possible using a Rake task (`rake generate:definitions`, https://github.com/YorickPeterse/ruby-lint/blob/1d036ca52d91256b1cf0f1d84dc025fdefe5e58a/task/generate.rake#L3) but only works for methods/constants defined in a top-level constant, e.g. definitions for global methods can't be generated easily.

Since this isn't really a bug I'll close this one.
